# Global namespace used for all charts
namespace: helm-app

alb:
  fullnameOverride: alb-nginx
  replicaCount: 1
  backendHostTpl: frontend.helm-app
  image:
    repository: nginx
    tag: latest
  configMapName: alb-nginx-html
  tlsSecretName: alb-nginx-tls
  service:
    type: NodePort
    http:
      enabled: false
      port: 80
      targetPort: 80
      nodePort: 30100
    https:
      port: 443
      targetPort: 443
      nodePort: 31443

frontend:
  fullnameOverride: frontend
  replicaCount: 1
  image:
    repository: nginx
    tag: latest
    imagePullPolicy: Always
  containerPort: 80
  configMapName: frontend-html-config
  service:
    type: ClusterIP
    port: 80
    targetPort: 80

apiGateway:
  fullnameOverride: api-gateway
  replicaCount: 1
  image:
    repository: api-gateway
    tag: latest
    pullPolicy: Never
  containerPort: 8081
  service:
    type: NodePort
    port: 8081
    targetPort: 8081
    nodePort: 30081
  resources:
    requests:
      cpu: "40m"
    limits:
      cpu: "200m"

lambdaProducer:
  fullnameOverride: lambda-producer
  replicaCount: 1
  image:
    repository: lambda-producer
    tag: latest
    pullPolicy: Never
  containerPort: 4000
  service:
    type: ClusterIP
    port: 4000
    targetPort: 4000
