alb:
  name: alb-nginx
  replicaCount: 1
  namespace: helm-app
  backendHostTpl: "alb-nginx-frontend.{{ .Values.alb.namespace }}"
  image:
    repository: nginx
    tag: stable

  configMapName: alb-nginx-html
  tlsSecretName: alb-nginx-tls

  service:
    type: NodePort
    http:
      enabled: false
      port: 80
      targetPort: 80
      nodePort: 30100
    https:
      port: 443
      targetPort: 443
      nodePort: 31443

# ---------------------------
# Frontend chart values
# ---------------------------

replicaCount: 1

image:
  repository: nginx
  tag: alpine

containerPort: 80

configMapName: frontend-html-config

service:
  type: ClusterIP
  port: 80
  targetPort: 80

