alb:
  name: alb-nginx
  replicaCount: 1

  image:
    repository: nginx
    tag: stable

  configMapName: alb-nginx-config
  tlsSecretName: alb-nginx-tls

  service:
    type: NodePort
    http:
      port: 80
      targetPort: 80
      nodePort: 30080
    https:
      port: 443
      targetPort: 443
      nodePort: 30443
