apiVersion: v1
kind: ConfigMap
metadata:
  name: alb-nginx-config
  namespace: helm-app
data:
  default.conf: |
    server {
        listen 80;

        location / {
            proxy_pass http://frontend-frontend.helm-app.svc.cluster.local;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
