apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.alb.configMapName | default "alb-nginx-html" }}
  namespace: {{ .Release.Namespace | default "helm-app" }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
data:
  default.conf: |
    server {
        listen 80;

        location / {
            proxy_pass http://frontend-frontend.{{ .Release.Namespace }}.svc.cluster.local;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
