apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}
  namespace: {{ .Values.namespace }}
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>My Frontend</title>
    </head>
    <body>
      <h1>Hello from Helm Frontend!</h1>
    </body>
    </html>
