apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  selector:
    app: {{ include "frontend.name" . }}
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port | default 80 }}
      targetPort: {{ .Values.service.targetPort | default 80 }}
