apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rabbitmq.secretName }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: {{ .Values.rabbitmq.username | quote }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.rabbitmq.password | quote }}
